### ISSUE TITLE
Running 2 xteve containers with different ports and config dirs

### ISSUE THREAD

**Issue by yarafie** [SenexCrenshaw/xTeVe#18]
**Is your feature request related to a problem? Please describe.**
How can I modify the docker_file.yml to run 2 different containers with 2 different ports and config directory?

**Describe the solution you'd like**
Would like an example of 2 differnt yml files

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SenexCrenshaw** [comment]
There are a few ways. Example using  docker-compose:
```
version: "2.1"
services:
  xteve1:
    image: senexcrenshaw/xteve:latest
    container_name: xteve
    environment:
      - TZ=America/New_York
    volumes:
      - /opt/configs/xteve1/config:/home/xteve/conf
      - /tmp/xteve1:/tmp/xteve:rw
    ports:
      - 34400:34400
    restart: unless-stopped

  xteve2:
    image: senexcrenshaw/xteve:latest
    container_name: xteve
    environment:
      - TZ=America/New_York
    volumes:
      - /opt/configs/xteve2/config:/home/xteve/conf
      - /tmp/xteve2:/tmp/xteve:rw
    ports:
      - 34401:34400
    restart: unless-stopped
```
